# Generated by Django 4.1.4 on 2023-01-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobreviventes',
            name='sobreviventes',
        ),
    ]
