# Generated by Django 4.1.4 on 2023-01-15 00:51

from django.db import migrations, models
import django.utils.timezone
import sobreviventes.models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_remove_sobreviventes_sobreviventes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobreviventes',
            name='sobreviventes',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name=sobreviventes.models.Sobreviventes),
            preserve_default=False,
        ),
    ]
