# Generated by Django 4.1.4 on 2023-01-16 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0003_alter_sobreviventes_localizacao'),
        ('relatorio', '0003_sobreviventes_sobreviventes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobreviventes',
            name='sobreviventes',
        ),
        migrations.AddField(
            model_name='sobreviventes',
            name='sobrevivente',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sobreviventes.sobreviventes'),
            preserve_default=False,
        ),
    ]
