# Generated by Django 4.1.4 on 2023-01-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sobreviventes', '0003_alter_sobreviventes_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('TMED', 'Trocar por medicação'), ('TM', 'Trocar munição'), ('TA', 'Trocar por água'), ('TAL', 'Trocar por alimento')], max_length=50)),
                
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('quant', models.IntegerField()),
                ('finalizado', models.BooleanField(default=False)),
                ('categoria_comercio', models.ManyToManyField(to='servicos.categoriacomercio')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sobreviventes.inventario')),
                ('sobrevivente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sobreviventes.sobreviventes')),
            ],
        ),
    ]
