# Generated by Django 4.1.4 on 2023-01-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacomercio',
            name='preco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categoriacomercio',
            name='titulo',
            field=models.CharField(choices=[('TMED', 'Trocar por medicação'), ('TM', 'Trocar munição'), ('TA', 'Trocar por água'), ('TAL', 'Trocar por alimento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
