# Generated by Django 4.1.4 on 2023-01-14 22:14

from django.db import migrations, models
import servicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_categoriacomercio_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='item',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='quant',
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.IntegerField(default=0, verbose_name=servicos.models.CategoriaComercio),
        ),
        migrations.AlterField(
            model_name='categoriacomercio',
            name='preco',
            field=models.IntegerField(default=0),
        ),
    ]
