# Generated by Django 4.1.4 on 2023-01-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobreviventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField(max_length=3)),
                ('sexo', models.CharField(max_length=10)),
                ('localizacao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('quant', models.IntegerField(max_length=3)),
                ('sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobreviventes.sobreviventes')),
            ],
        ),
    ]
