# Generated by Django 4.1.4 on 2023-01-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='quant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sobreviventes',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
