# Generated by Django 4.1.4 on 2023-01-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0002_alter_inventario_quant_alter_sobreviventes_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobreviventes',
            name='localizacao',
            field=models.CharField(max_length=100),
        ),
    ]
